#!/bin/bash

cd /etc
valor=`cat /usr/local/bin/count.txt`
logfile="/var/log/filectl.log"

git config user.email “meunome@email.com.br”
git config user.name “Usuario”
etckeeper commit "Alteracao $valor - Arquivo $1 Operacao $2 Diretorio $3" 

valor=$((valor+1))
echo $valor > /usr/local/bin/count.txt
